/*
 * splitflap_pins.h
 *
 *  Created on: 29.09.2022
 *      Author: jonas
 */

#ifndef SPLITFLAP_PINS_H_
#define SPLITFLAP_PINS_H_

/* Magnet sensor */
#define MAG_MOTOR0_GPIO 	GPIOB
#define MAG_MOTOR0_PORT 	PORTB
#define MAG_MOTOR0_PIN 		19U

#define MAG_MOTOR1_GPIO 	GPIOB
#define MAG_MOTOR1_PORT 	PORTB
#define MAG_MOTOR1_PIN 		18U

#define MAG_MOTOR2_GPIO 	GPIOA
#define MAG_MOTOR2_PORT 	PORTA
#define MAG_MOTOR2_PIN 		13U

#define MAG_MOTOR3_GPIO 	GPIOB
#define MAG_MOTOR3_PORT 	PORTB
#define MAG_MOTOR3_PIN 		3U

/* motor 0 */
#define STEPPER_MOTOR0_IN1_GPIO		GPIOC
#define STEPPER_MOTOR0_IN1_PORT		PORTC
#define STEPPER_MOTOR0_IN1_PIN		11U

#define STEPPER_MOTOR0_IN2_GPIO		GPIOC
#define STEPPER_MOTOR0_IN2_PORT		PORTC
#define STEPPER_MOTOR0_IN2_PIN		10U

#define STEPPER_MOTOR0_IN3_GPIO		GPIOC
#define STEPPER_MOTOR0_IN3_PORT		PORTC
#define STEPPER_MOTOR0_IN3_PIN		9U

#define STEPPER_MOTOR0_IN4_GPIO		GPIOC
#define STEPPER_MOTOR0_IN4_PORT		PORTC
#define STEPPER_MOTOR0_IN4_PIN		8U

/* motor 1 */
#define STEPPER_MOTOR1_IN1_GPIO		GPIOA
#define STEPPER_MOTOR1_IN1_PORT		PORTA
#define STEPPER_MOTOR1_IN1_PIN		1U

#define STEPPER_MOTOR1_IN2_GPIO		GPIOA
#define STEPPER_MOTOR1_IN2_PORT		PORTA
#define STEPPER_MOTOR1_IN2_PIN		2U

#define STEPPER_MOTOR1_IN3_GPIO		GPIOA
#define STEPPER_MOTOR1_IN3_PORT		PORTA
#define STEPPER_MOTOR1_IN3_PIN		5U

#define STEPPER_MOTOR1_IN4_GPIO		GPIOA
#define STEPPER_MOTOR1_IN4_PORT		PORTA
#define STEPPER_MOTOR1_IN4_PIN		12U

/* TODO define motors 2 and 3 */

#endif /* SPLITFLAP_PINS_H_ */
